// <auto-generated />
using System;
using DataLayer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250428231329_UpdateService")]
    partial class UpdateService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLayer.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DisconuntPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PayPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("DataLayer.Models.ContractDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DisconuntPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ContractDetails");
                });

            modelBuilder.Entity("DataLayer.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DataLayer.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceSettingId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId");

                    b.HasIndex("ServiceSettingId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("DataLayer.Models.ServiceLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "1"
                        },
                        new
                        {
                            Id = 2,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "2"
                        },
                        new
                        {
                            Id = 3,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "3"
                        },
                        new
                        {
                            Id = 4,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "4"
                        },
                        new
                        {
                            Id = 5,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "5"
                        },
                        new
                        {
                            Id = 6,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "6"
                        },
                        new
                        {
                            Id = 7,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "7"
                        },
                        new
                        {
                            Id = 8,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "8"
                        },
                        new
                        {
                            Id = 9,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "9"
                        },
                        new
                        {
                            Id = 10,
                            City = "Guatemala",
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Zone = "10"
                        });
                });

            modelBuilder.Entity("DataLayer.Models.ServiceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServiceSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Description = "Velocidad de internet",
                            IsActive = true,
                            Name = "Velocidad 15Mbps",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Description = "Velocidad de internet",
                            IsActive = true,
                            Name = "Velocidad 25Mbps",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Description = "Velocidad de internet",
                            IsActive = true,
                            Name = "Velocidad 50Mbps",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Description = "Servicio de cable",
                            IsActive = true,
                            Name = "Basico 100 canales",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            Description = "Servicio de cable",
                            IsActive = true,
                            Name = "Premium canales adicionaels",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Cable",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            Name = "Internet",
                            UpdatedAt = new DateTime(2025, 4, 28, 10, 35, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("DataLayer.Models.Contract", b =>
                {
                    b.HasOne("DataLayer.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DataLayer.Models.ContractDetail", b =>
                {
                    b.HasOne("DataLayer.Models.Contract", "Contract")
                        .WithMany("ContractDetails")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataLayer.Models.Service", b =>
                {
                    b.HasOne("DataLayer.Models.ServiceLocation", "ServiceLocation")
                        .WithMany()
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.ServiceSetting", "ServiceSetting")
                        .WithMany()
                        .HasForeignKey("ServiceSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLayer.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceLocation");

                    b.Navigation("ServiceSetting");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("DataLayer.Models.Contract", b =>
                {
                    b.Navigation("ContractDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
